// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5506.Stronghold;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Victor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainleftMotors;
    public static SpeedController driveTrainrightMotors;
    public static RobotDrive driveTrainmotors;
    public static CANTalon liftLiftMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainleftMotors = new Victor(0);
        LiveWindow.addActuator("DriveTrain", "leftMotors", (Victor) driveTrainleftMotors);
        
        driveTrainrightMotors = new Victor(1);
        LiveWindow.addActuator("DriveTrain", "rightMotors", (Victor) driveTrainrightMotors);
        
        driveTrainmotors = new RobotDrive(driveTrainleftMotors, driveTrainrightMotors);
        
        driveTrainmotors.setSafetyEnabled(true);
        driveTrainmotors.setExpiration(0.1);
        driveTrainmotors.setSensitivity(0.5);
        driveTrainmotors.setMaxOutput(1.0);

        liftLiftMotor = new CANTalon(2);
        LiveWindow.addActuator("Lift", "LiftMotor", liftLiftMotor);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
