// Generated by CoffeeScript 1.10.0
(function() {
  var a, d, f, s, step;

  f = function(time, start, change, dur) {
    time /= dur;
    return change * (time ^ 3) + start;
  };

  a = 0;

  s = 0;

  d = 100;

  step = function(frame) {
    if (frame < 200) {
      setTimeout(step(frame + 1), 100);
    }
    a = f(frame, s, 100, d);
    return console.log((f * 10) + "ms\t" + a + "%");
  };

  step();

}).call(this);
